# Generated by Django 3.2.6 on 2022-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movieName', models.CharField(default=None, max_length=255)),
                ('genreId', models.CharField(default=None, max_length=255)),
                ('movieType', models.CharField(default=None, max_length=255)),
                ('movieId', models.CharField(max_length=255, unique=True)),
                ('overview', models.TextField(default=None)),
                ('releaseDate', models.CharField(default=None, max_length=255)),
                ('language', models.CharField(default=None, max_length=255)),
                ('popularity', models.CharField(default=None, max_length=255)),
                ('voteAverage', models.CharField(default=None, max_length=255)),
                ('voteCount', models.CharField(default=None, max_length=255)),
                ('posterPath', models.CharField(default=None, max_length=255)),
                ('backdropPath', models.CharField(default=None, max_length=255)),
                ('watchCount', models.CharField(default=None, max_length=255)),
                ('watchTime', models.CharField(default=None, max_length=255)),
                ('teaser', models.CharField(default=None, max_length=255)),
                ('movieURL', models.CharField(default=None, max_length=255)),
                ('favourite', models.CharField(default=None, max_length=255)),
                ('user', models.CharField(default=None, max_length=255)),
                ('uploadedOn', models.DateTimeField(blank=True, null=True)),
                ('modifiedOn', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
